// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpwiwiahcophvootjgdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwd2l3aWFoY29waHZvb3RqZ2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzUxNDAsImV4cCI6MjA2NzA1MTE0MH0.0MHRtp8_sJconImOFLHGjTOMgMV923CNwwsaUY8_tvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});